### ISSUE TITLE
Sysmon v11.0 04/28/2020

### ISSUE THREAD

**Issue by jeff-cook** [S3COPS/ArcSight-Sysmon-FlexConnector#13]
Sysmon version 11.0 was released on 04/28/2020.

A new event ID was added. 
23 FileDelete 
The parser will need to be updated for this. 

I'm not sure what else has changed with this version.

Field | Description
-- | --
UtcTime | Time in UTC when event was created
ProcessGuid | Process Guid of the process that made the delete
ProcessId | Process ID of the process that made the delete
User | User that created the
Image | File path of the process that made the
TargetFilename | Name of the file that was deleted
Hashes | Full hash of the file with the algorithms in the HashType field
IsExecutable | Boolean Value if deleted file was executable
Archived | Boolean Value if deleted file was archived in the ArchiveDirectory folder based on the CopyOnDelete* settings

**Comment by S3COPS** [comment]
Will review and update - thanks

**Comment by S3COPS** [comment]
Updated - thanks
