### ISSUE TITLE
use filePath instead of fileName

### ISSUE THREAD

**Issue by klasen** [S3COPS/ArcSight-Sysmon-FlexConnector#6]
EventData elements such as Image contain the full path to the file. Therefore, these need to be mapped to (old)FilePath instead of (old)fileName.

(old)fileName: Name of the file only (without its path).
(old)FilePath: Full path to the file, including file name itself. Example: C:\Program Files\WindowsNT\Accessories\ wordpad.exe or /usr/bin/zip

**Comment by S3COPS** [comment]
Accepted - Thanks for the feedback
